---
collections:
  - amazon.aws
  - community.general
  - ansible.posix

roles:
# from GitLab or other git-based scm, using git+ssh
- src: https://gitlab.epfl.ch/ecps/ansible_basics.git
  scm: git
  name: basics

- src: https://gitlab.epfl.ch/ecps/ansible_mathematica.git
  scm: git
  name: mathematica

- src: https://gitlab.epfl.ch/ecps/ansible_matlab.git
  scm: git
  name: matlab

- src: https://gitlab.epfl.ch/ecps/ansible_ldap_authentication.git
  scm: git
  name: ansible_ldap

- src: https://gitlab.epfl.ch/ecps/ansible_sudo.git
  scm: git
  name: ansible_sudo

- src: https://gitlab.epfl.ch/ecps/ansible_slurmclient.git
  scm: git
  name: ansible_slurmclient

- src: https://gitlab.epfl.ch/ecps/ansible_mountFileserver.git
  scm: git
  name: ansible_mountFileserver
